language: java
install: true

dist: trusty
jdk: openjdk8

before_install:
  - chmod +x gradlew
script:
  - ./gradlew build --stacktrace
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
