language: java
install: true

dist: trusty
jdk: openjdk8

before_install:
  - wget http://services.gradle.org/distributions/gradle-5.3-bin.zip
  - unzip -qq gradle-5.3-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.3
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
  - if [[ $COVERAGE == "" ]]; then phpenv config-rm xdebug.ini; fi
script:
  - gradle clean build --scan -s
  - gradle jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
