language: java
install: true

dist: trusty
jdk: openjdk8

before_install:
  - wget http://services.gradle.org/distributions/gradle-6.0.1-bin.zip
  - unzip -qq gradle-6.0.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.0.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
script:
  - gradle clean build --debug --scan -s
  - gradle jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
